UsePermissions: true
UseCatchChance: true
LooseEggOnFail: true
UseVaultCost: false
UseItemCost: false
UseHealthPercentage: false
ExplosionEffect: true
SmokeEffect: false
NonPlayerCatching: false
PreventCatchingBabyAnimals: true
PreventCatchingTamedAnimals: true
PreventCatchingShearedSheeps: true
SpawnChickenOnSuccess: false
SpawnChickenOnFail: true
VaultTargetBankAccount: ""
DeleteVillagerInventoryOnCatch: false
LogEggCaptures: false
CatchChance:
  BAT: 100.0
  BLAZE: 100.0
  CAVE_SPIDER: 100.0
  CHICKEN: 100.0
  COD: 100.0
  COW: 100.0
  CREEPER: 100.0
  DOLPHIN: 100.0
  DONKEY: 100.0
  DROWNED: 100.0
  ELDER_GUARDIAN: 100.0
  ENDERMAN: 100.0
  ENDERMITE: 100.0
  EVOKER: 100.0
  GHAST: 100.0
  GUARDIAN: 100.0
  HORSE: 100.0
  HUSK: 100.0
  LLAMA: 100.0
  MAGMA_CUBE: 100.0
  MUSHROOM_COW: 100.0
  MULE: 100.0
  OCELOT: 100.0
  PARROT: 100.0
  PHANTOM: 100.0
  PIG: 100.0
  PIG_ZOMBIE: 100.0
  POLAR_BEAR: 100.0
  PUFFERFISH: 100.0
  RABBIT: 100.0
  SALMON: 100.0
  SHEEP: 100.0
  SHULKER: 100.0
  SILVERFISH: 100.0
  SKELETON_HORSE: 100.0
  SKELETON: 100.0
  SLIME: 100.0
  SPIDER: 100.0
  SQUID: 100.0
  STRAY: 100.0
  TROPICAL_FISH: 100.0
  TURTLE: 100.0
  VEX: 100.0
  VILLAGER: 100.0
  VINDICATOR: 100.0
  WITCH: 100.0
  WITHER_SKELETON: 100.0
  WOLF: 100.0
  ZOMBIE_HORSE: 100.0
  ZOMBIE: 100.0
  ZOMBIE_VILLAGER: 100.0
VaultCost:
  BAT: 0.0
  BLAZE: 0.0
  CAVE_SPIDER: 0.0
  CHICKEN: 0.0
  COD: 0.0
  COW: 0.0
  CREEPER: 0.0
  DOLPHIN: 0.0
  DONKEY: 0.0
  DROWNED: 0.0
  ELDER_GUARDIAN: 0.0
  ENDERMAN: 0.0
  ENDERMITE: 0.0
  EVOKER: 0.0
  GHAST: 0.0
  GUARDIAN: 0.0
  HORSE: 0.0
  HUSK: 0.0
  LLAMA: 0.0
  MAGMA_CUBE: 0.0
  MUSHROOM_COW: 0.0
  MULE: 0.0
  OCELOT: 0.0
  PARROT: 0.0
  PHANTOM: 0.0
  PIG: 0.0
  PIG_ZOMBIE: 0.0
  POLAR_BEAR: 0.0
  PUFFERFISH: 0.0
  RABBIT: 0.0
  SALMON: 0.0
  SHEEP: 0.0
  SHULKER: 0.0
  SILVERFISH: 0.0
  SKELETON_HORSE: 0.0
  SKELETON: 0.0
  SLIME: 0.0
  SPIDER: 0.0
  SQUID: 0.0
  STRAY: 0.0
  TROPICAL_FISH: 0.0
  TURTLE: 0.0
  VEX: 0.0
  VILLAGER: 0.0
  VINDICATOR: 0.0
  WITCH: 0.0
  WITHER_SKELETON: 0.0
  WOLF: 0.0
  ZOMBIE_HORSE: 0.0
  ZOMBIE: 0.0
  ZOMBIE_VILLAGER: 0.0
ItemCost:
  ItemName: GOLD_NUGGET
  Amount:
    BAT: 0
    BLAZE: 0
    CAVE_SPIDER: 0
    CHICKEN: 0
    COD: 0
    COW: 0
    CREEPER: 0
    DOLPHIN: 0
    DONKEY: 0
    DROWNED: 0
    ELDER_GUARDIAN: 0
    ENDERMAN: 0
    ENDERMITE: 0
    EVOKER: 0
    GHAST: 0
    GUARDIAN: 0
    HORSE: 0
    HUSK: 0
    LLAMA: 0
    MAGMA_CUBE: 0
    MUSHROOM_COW: 0
    MULE: 0
    OCELOT: 0
    PARROT: 0
    PHANTOM: 0
    PIG: 0
    PIG_ZOMBIE: 0
    POLAR_BEAR: 0
    PUFFERFISH: 0
    RABBIT: 0
    SALMON: 0
    SHEEP: 0
    SHULKER: 0
    SILVERFISH: 0
    SKELETON_HORSE: 0
    SKELETON: 0
    SLIME: 0
    SPIDER: 0
    SQUID: 0
    STRAY: 0
    TROPICAL_FISH: 0
    TURTLE: 0
    VEX: 0
    VILLAGER: 0
    VINDICATOR: 0
    WITCH: 0
    WITHER_SKELETON: 0
    WOLF: 0
    ZOMBIE_HORSE: 0
    ZOMBIE: 0
    ZOMBIE_VILLAGER: 0
HealthPercentage:
  BAT: 100.0
  BLAZE: 100.0
  CAVE_SPIDER: 100.0
  CHICKEN: 100.0
  COD: 100.0
  COW: 100.0
  CREEPER: 100.0
  DOLPHIN: 100.0
  DONKEY: 100.0
  DROWNED: 100.0
  ELDER_GUARDIAN: 100.0
  ENDERMAN: 100.0
  ENDERMITE: 100.0
  EVOKER: 100.0
  GHAST: 100.0
  GUARDIAN: 100.0
  HORSE: 100.0
  HUSK: 100.0
  LLAMA: 100.0
  MAGMA_CUBE: 100.0
  MUSHROOM_COW: 100.0
  MULE: 100.0
  OCELOT: 100.0
  PARROT: 100.0
  PHANTOM: 100.0
  PIG: 100.0
  PIG_ZOMBIE: 100.0
  POLAR_BEAR: 100.0
  PUFFERFISH: 100.0
  RABBIT: 100.0
  SALMON: 100.0
  SHEEP: 100.0
  SHULKER: 100.0
  SILVERFISH: 100.0
  SKELETON_HORSE: 100.0
  SKELETON: 100.0
  SLIME: 100.0
  SPIDER: 100.0
  SQUID: 100.0
  STRAY: 100.0
  TROPICAL_FISH: 100.0
  TURTLE: 100.0
  VEX: 100.0
  VILLAGER: 100.0
  VINDICATOR: 100.0
  WITCH: 100.0
  WITHER_SKELETON: 100.0
  WOLF: 100.0
  ZOMBIE_HORSE: 100.0
  ZOMBIE: 100.0
  ZOMBIE_VILLAGER: 100.0
Messages:
  PermissionFail: "You do not have permission to catch this mob!"
  VaultFail: "It costs %s dollars to catch this mob!"
  VaultSuccess: "You paid %s dollars for catching this mob!"
  ItemCostFail: "It costs %s gold nugget(s) to catch this mob!"
  ItemCostSuccess: "You paid %s gold nugget(s) for catching this mob!"
  CatchChanceFail: "You failed to catch this mob!"
  CatchChanceSuccess: ""
  HealthPercentageFail: "The mob has more than %s percent health left and cannot be caught!"
ConfigVersion: 4.0
